# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, Mark LaPointe <mark@cloudbsd.org>

PACKAGE=	tests
TESTSDIR=	${TESTSBASE}/sys/modules/hyrule

ATF_TESTS_SH=	hyrule_test

.include <bsd.test.mk>
